Gift and Salary cards/Controllers/CardController.cs
using Gift_and_Salary_cards.Models.Identity;
using Gift_and_Salary_cards.Models.ViewModels;
using Gift_and_Salary_cards.Services;
using Gift_and_Salary_cards.Services.ComissionService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Yandex.Checkout.V3;

namespace Gift_and_Salary_cards.Controllers
{

    [Authorize]
    public class CardController : Controller
    {

        private readonly UserManager<User> _userManager;
        private readonly IUKassaServicePayout ukassaServicePayout;
        private readonly IUkassaServicePayment ukassaServicePayment;
        private readonly IPaymentService paymentService;
        private readonly IComissionService comissionService;



        public CardController(IPaymentService paymentService, IUKassaServicePayout ukassaServicePayout, UserManager<User> userManager, IUkassaServicePayment ukassaServicePayment, IComissionService comissionService)
        {
            this.paymentService = paymentService;
            this.ukassaServicePayout = ukassaServicePayout;
            _userManager = userManager;
            this.ukassaServicePayment = ukassaServicePayment;
            this.comissionService = comissionService;
        }


        /// <summary>
        /// Страница зарплатной карты
        /// </summary>
        /// <returns></returns>
        
        public IActionResult SalaryCard()
        {
            return View();
        }


        /// <summary>
        /// Пополнение банковской карты сотрудника
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> PaymentBankCard(PaymentFormViewModel model)
        {

            // Если данные на форме введены успешно, то необходимо приступить к дальнейшей логике
            if (ModelState.IsValid)
            {
                // Получаем синоним банковской карты
                var synonimCard = ukassaServicePayout.GetSynonimCard(model.bankCardNumber);

                // Если банковская карта не найдена, то вернуть ошибку об этом
                if (synonimCard == null)
                {
                    ModelState.AddModelError("bankCardNumber", "Банковская карта не существует!");

                    return View("SalaryCard", model);
                }

                // Если банковская карта найдена и получили ее синоним от юкассы, то создать ссылку для оплаты
                // И сохранить данные в базе данных по оплате с соответствующим статусом
                var userAuth = await _userManager.GetUserAsync(User);

                var getLastComission = await comissionService.getProcentComission();

                // Сумма выплаты с учетом процентов
                model.moneyPayProcent = (model.moneyPay / 100 * getLastComission.Procent.Value) + model.moneyPay;

                // Создаем платеж для пользователя
                var payment = ukassaServicePayment.createPayment(model, userAuth);

                if (payment != null)
                {



                    // Формируем платежку для бд
                    Models.DataBase.Payment payDb = new Models.DataBase.Payment()
                    {
                        PayerEmail = userAuth.Email,
                        PayerPhone = userAuth.phone,
                        Description = model.textPayment,
                        SumPayment = model.moneyPayProcent,
                        PaymentUserId = userAuth.Id,
                        IdUkassa = payment.Id,
                        IdComission = getLastComission.Id, // Задаем комиссию

                        // Сразу задаем в списке, что платежка создана
                        PaymentStatuses = new List<Models.DataBase.PaymentStatus>()
                        {
                            new Models.DataBase.PaymentStatus()
                            {
                                DateStatus = DateTime.Now,
                                StatusPaymentId = 1,                                
                            }
                        },

                        AddressEmp = model.address,
                        DateBirthEmp = model.dateBirth,
                        DocIssueDateEmp = model.docIssueDate,
                        DocNumberEmp = model.docNumber,
                        CityEmp = model.city,
                        NameEmp = model.Name,
                        SurnameEmp = model.Surname,
                        FamilyEmp = model.Family,
                        CountryEmp = model.country,
                        MoneyPayEmployee = model.moneyPay,
                        PhoneNumberEmp = model.PhoneNumber,
                        PostcodeEmp = model.postcode,
                        CardBank = new Models.DataBase.CardBank()
                        {
                            NumberCard = model.bankCardNumber
                        }
                    };

                    // Теперь сохраняем в базе данных платежку и кидаем пользователя на страницу оплаты
                    bool addDataBase = paymentService.AddPayment(payDb);

                    if (addDataBase == false)
                    {
                        return BadRequest("Ошибка добавления платежа в базу данных");
                    }

                    // Иначе кидаем на страницу оплаты
                    return Redirect(payment.Confirmation.ConfirmationUrl);
                }
            }


            return View("SalaryCard", model);
        }







    }
}

Gift and Salary cards/Controllers/OfertaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Gift_and_Salary_cards.Controllers
{
    public class OfertaController : Controller
    {
        public OfertaController()
        {

        }

        public IActionResult Oferta()
        {


            return View();
        }
    }
}

Gift and Salary cards/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Gift_and_Salary_cards.Controllers
{

    [Authorize]
    public class ProfileController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Gift and Salary cards/Controllers/RolesController.cs
using Gift_and_Salary_cards.Models.Identity;
using Gift_and_Salary_cards.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Gift_and_Salary_cards.Controllers
{

    [Authorize(Roles = "Администратор")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();

            return View(roles);
        }

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }

}

Gift and Salary cards/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>virtcards - @ViewData["Title"]</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    @await RenderSectionAsync("Css", required: false)
</head>
<body>
    <header>
        <nav class="navbar nav mb-3 fixed-top navbar-expand-md navbar-toggleable-md navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">virtcards</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-md-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link btn text-dark active" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Корпоратив"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link btn text-dark" href="#payment">Подарочные карты</a>
                                </li>
                            }
                        }
                        <li class="nav-item">
                            <a class="nav-link btn text-dark" asp-controller="Card" asp-action="SalaryCard">Зарплатные карты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn text-dark" asp-controller="Contacts" asp-action="Index">Контакты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn text-dark" asp-controller="Oferta" asp-action="Oferta">Оферта</a>
                        </li>
                    </ul>
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="dropdown open d-none d-lg-block mt-lg-0 mt-3">
                        <button class="btn dropdown-toggle phone-number" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @User.Identity.Name
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a asp-controller="Profile" asp-action="Index" class="dropdown-item">Профиль</a>
                            @if (User.IsInRole("Администратор"))
                            {
                                <a asp-controller="Roles" asp-action="Index" class="dropdown-item">Роли пользователей</a>
                            }
                            <div class="dropdown-divider"></div>
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <input class="dropdown-item" type="submit" value="Выход" />
                            </form>
                        </div>
                    </div>
                }
                else
                {
                    <a class="btn phone-number d-none d-lg-block" asp-action="Login" asp-controller="Account">Войти</a>
                }

            </div>
            <div class="container text-center d-block d-md-none">
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="dropdown open mt-lg-0 mt-3">
                        <button class="btn dropdown-toggle phone-number w-100" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @User.Identity.Name
                        </button>
                        <div class="dropdown-menu w-100 text-center" aria-labelledby="dropdownMenuButton">
                            <a asp-controller="Profile" asp-action="Index" class="dropdown-item">Профиль</a>
                            @if (User.IsInRole("Администратор"))
                            {
                                <a asp-controller="Roles" asp-action="Index" class="dropdown-item">Роли пользователей</a>
                            }
                            <div class="dropdown-divider"></div>
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <input class="dropdown-item" type="submit" value="Выход" />
                            </form>
                        </div>
                    </div>
                }
                else
                {
                    <a class="btn phone-number w-25" asp-action="Login" asp-controller="Account">Войти</a>
                }
            </div>
        </nav>
    </header>
    <div class="container-fluid p-0 main-content">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2013-2021 - ООО "Абрис М" - <a asp-area="" asp-controller="Contacts" asp-action="Index">контакты</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/scripts/chunk-vendors.js" asp-append-version="true"></script>
    <script src="~/js/activemenu.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Gift and Salary cards/Views/Shared/_LayoutProfile.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>virtcards - @ViewData["Title"]</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/css/profile.css" rel="stylesheet" asp-append-version="true" />
    @await RenderSectionAsync("Css", required: false)
</head>
<body>
    <header>
        <nav class="navbar nav mb-3 fixed-top navbar-expand-md navbar-toggleable-md navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">virtcards</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-md-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link btn text-dark active" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Корпоратив"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link btn text-dark" href="#payment">Подарочные карты</a>
                                </li>
                            }
                        }
                        <li class="nav-item">
                            <a class="nav-link btn text-dark" asp-controller="Card" asp-action="SalaryCard">Зарплатные карты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn text-dark" asp-controller="Contacts" asp-action="Index">Контакты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn text-dark" asp-controller="Oferta" asp-action="Oferta">Оферта</a>
                        </li>
                    </ul>
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="dropdown open d-none d-lg-block mt-lg-0 mt-3">
                        <button class="btn dropdown-toggle phone-number" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @User.Identity.Name
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a asp-controller="Profile" asp-action="Index" class="dropdown-item">Профиль</a>
                            @if (User.IsInRole("Администратор"))
                            {
                                <a asp-controller="Roles" asp-action="Index" class="dropdown-item">Роли пользователей</a>
                            }
                            <div class="dropdown-divider"></div>
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <input class="dropdown-item" type="submit" value="Выход" />
                            </form>
                        </div>
                    </div>
                }
                else
                {
                    <a class="btn phone-number d-none d-lg-block" asp-action="Login" asp-controller="Account">Войти</a>
                }

            </div>
            <div class="container text-center d-block d-md-none">
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="dropdown open mt-lg-0 mt-3">
                        <button class="btn dropdown-toggle phone-number w-100" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @User.Identity.Name
                        </button>
                        <div class="dropdown-menu w-100 text-center" aria-labelledby="dropdownMenuButton">
                            <a asp-controller="Profile" asp-action="Index" class="dropdown-item">Профиль</a>
                            @if (User.IsInRole("Администратор"))
                            {
                                <a asp-controller="Roles" asp-action="Index" class="dropdown-item">Роли пользователей</a>
                            }
                            <div class="dropdown-divider"></div>
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <input class="dropdown-item" type="submit" value="Выход" />
                            </form>
                        </div>
                    </div>
                }
                else
                {
                    <a class="btn phone-number w-25" asp-action="Login" asp-controller="Account">Войти</a>
                }
            </div>
        </nav>
    </header>
    <div class="container-fluid p-0 main-content">
        <main role="main">
            <div class="container-fluid p-0 profile-block">


                <div class="row m-0">
                    <div class="menu col-12 col-lg-3 p-0">
                        <ul class="list-unstyled m-0">
                            <a href="#"><li class="item-menu item-menu-active p-3">Профиль</li></a>
                            <a href="#"><li class="item-menu p-3">Выплаты</li></a>
                            <a href="#"><li class="item-menu p-3">Мои сотрудники</li></a>
                        </ul>
                    </div>
                    <div class="col-12 col-lg-9">
                        @RenderBody()
                    </div>
                </div>



            </div>

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2013-2021 - ООО "Абрис М" - <a asp-area="" asp-controller="Contacts" asp-action="Index">контакты</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/scripts/chunk-vendors.js" asp-append-version="true"></script>
    <script src="~/js/activemenu.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>